blank_issues_enabled: false
contact_links:
  - name: codinit.new related issues
    url: https://github.com/gerome-elassaad/codinit-app/issues/new/choose
    about: Report issues related to codinit.dev
